# Generated by Django 2.2.9 on 2020-09-02 19:54

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200902_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name=posts.models.Group),
        ),
    ]
